### ISSUE TITLE
Lack 'poas_seeds.csv' for replicating results.

### ISSUE THREAD

**Issue by EvaFlower** [ngruver/NOS#3]
Hi,

Your work is really interesting and thanks for sharing your code. 

I have been trying to replicate your paper results to better understand your work. Following the readme, I found the poas_seeds.csv is lacking for replicate the infilling and guidance experiments.

Could you please consider uploading the file or providing the instruction to prepare poas_seeds.csv? I have tried the poas_seeds.txt but it seems inappropriate.

Thanks!

**Comment by ngruver** [comment]
Sorry for the delay and for the original oversight! I've added the file here: https://github.com/ngruver/NOS/blob/main/poas_seeds.csv. 

Please let me know if you have any other problems with the code!

Nate
